on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out current repository
        uses: actions/checkout@v3

      - name: Fake deploy
        run: echo "Running fake deploy for version ${{ inputs.version }}..."