on:
  workflow_dispatch:

jobs:
  run-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out current repository
        uses: actions/checkout@v3

      - name: Fake release
        run: echo "Running fake release ..."

      - name: Call other files
        uses: ./.github/workflows/deploy.yml@main