on:
  workflow_dispatch:

jobs:
  run-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out current repository
        uses: actions/checkout@v3

      - name: Fake release
        run: echo "Running fake release ..."


  call-deploy-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      version: 2.11.0
    needs:
      - run-release