on:
  workflow_dispatch:

jobs:
  run-release:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Check out current repository
        uses: actions/checkout@v3

      - name: Fake release
        run: echo "Running fake release ..."

      - name: Set app version
        run: echo "APP_VERSION=2.15.0" >> $GITHUB_ENV

      - name: Print
        run: echo "Version is ${APP_VERSION}"

      - name: Set app version
        id: branch
        run: echo "::set-output name=branch::release-2.15.0"

      - name: Set tag
        id: tag
        run: echo "::set-output name=tag::v2.15.0"

      - name: Add tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.tag.outputs.tag }}
          message: ${{ steps.tag.outputs.tag }}


  call-deploy-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.run-release.outputs.branch }}
    needs:
      - run-release