on:
  workflow_dispatch:

jobs:
  run-release:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.version.outputs.branch }}
      tag: ${{ steps.version.outputs.tag }}

    steps:
      - name: Check out current repository
        uses: actions/checkout@v3

      - name: Fake release
        run: echo "Running fake release ..."

      - name: Define release branch and tag
        id: version
        run: |
          echo "::set-output name=branch::release-2.16.0"
          echo "::set-output name=tag::v2.16.0"

      - name: Create release branch
        run: git checkout -b ${{ steps.version.outputs.branch }} && git push origin ${{ steps.version.outputs.branch }}

      - name: Add tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.tag }}
          message: ${{ steps.version.outputs.tag }}


  call-deploy-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.run-release.outputs.branch }}
    needs:
      - run-release